// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextCourses.Context;

namespace NextCourses.Migrations
{
    [DbContext(typeof(CourseContext))]
    partial class CourseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("NextCourses.Models.PrereqMap", b =>
                {
                    b.Property<string>("prereq_course_name");

                    b.Property<string>("next_course_name");

                    b.HasKey("prereq_course_name", "next_course_name");

                    b.ToTable("Prereqs");
                });

            modelBuilder.Entity("NextCourses.Models.UWCourse", b =>
                {
                    b.Property<string>("course_name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("catalog_number");

                    b.Property<string>("course_id");

                    b.Property<string>("subject");

                    b.Property<string>("title");

                    b.HasKey("course_name");

                    b.ToTable("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
